version: '3'
services:
  db:
    image: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - entidades-compose-network
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio_dock

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    networks:
      - entidades-compose-network
    links:
      - db
    ports:
      - 8000:80

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: samcefalo/desafio_dock:1.0
    links:
      - db
    networks:
      - entidades-compose-network
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  dbdata:

networks:
  entidades-compose-network:
    driver: bridge