version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: samcefalo/desafio_dock:1.0
    networks:
      - entidades-compose-network
    ports:
      - 8080:8080

networks:
  entidades-compose-network:
    driver: bridge