spring:
  datasource:
    url: jdbc:mysql://db:3306/desafio_dock?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    hibernate:
      jdbc: time_zone = TimeZone
    show-sql: true

server:
  error:
    include-message: always